In [1]:
import numpy as np

# Generate a 5x4 array of random integers between 1 and 50
np.random.seed(0)
arr = np.random.randint(1, 51, size=(5, 4))
print("Array:\n", arr)

# Extract anti-diagonal (top-right to bottom-left)
anti_diag = [arr[i, arr.shape[1]-1-i] for i in range(min(arr.shape))]
print("Anti-diagonal:", anti_diag)

# Maximum value in each row
row_max = arr.max(axis=1)
print("Row-wise max:", row_max)

# Elements less than or equal to mean
mean_val = arr.mean()
leq_mean = arr[arr <= mean_val]
print("Elements <= mean:", leq_mean)

# Boundary traversal function
def numpy_boundary_traversal(matrix):
    m, n = matrix.shape
    result = []
    # Top row
    result.extend(matrix[0, :])
    # Right column
    result.extend(matrix[1:m-1, -1])
    # Bottom row (reversed)
    if m > 1:
        result.extend(matrix[m-1, ::-1])
    # Left column (reversed)
    if n > 1:
        result.extend(matrix[m-2:0:-1, 0])
    return list(result)

boundary = numpy_boundary_traversal(arr)
print("Boundary traversal:", boundary)


Array:
 [[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]
 [39 40 24 47]]
Anti-diagonal: [4, 10, 37, 25]
Row-wise max: [48 40 37 25 47]
Elements <= mean: [ 1  4  4 10 20 22  7 13  2]
Boundary traversal: [45, 48, 1, 4, 20, 7, 2, 47, 24, 40, 39, 25, 22, 4]


In [2]:
# Generate 1D array of 20 random floats between 0 and 10
arr1d = np.random.uniform(0, 10, 20)
print("Original array:", arr1d)

# Round to two decimal places
arr1d_rounded = np.round(arr1d, 2)
print("Rounded:", arr1d_rounded)

# Min, max, median
print("Min:", arr1d.min())
print("Max:", arr1d.max())
print("Median:", np.median(arr1d))

# Replace elements < 5 with their squares
arr1d_sq = arr1d.copy()
arr1d_sq[arr1d_sq < 5] = arr1d_sq[arr1d_sq < 5] ** 2
print("After squaring elements < 5:", arr1d_sq)

# Alternate sort function
def numpy_alternate_sort(array):
    arr_sorted = np.sort(array)
    result = []
    left, right = 0, len(arr_sorted) - 1
    while left <= right:
        result.append(arr_sorted[left])
        left += 1
        if left <= right:
            result.append(arr_sorted[right])
            right -= 1
    return np.array(result)

alt_sorted = numpy_alternate_sort(arr1d)
print("Alternately sorted:", alt_sorted)


Original array: [5.68044561 9.25596638 0.71036058 0.871293   0.20218397 8.32619846
 7.78156751 8.70012148 9.78618342 7.99158564 4.61479362 7.80529176
 1.18274426 6.39921021 1.43353287 9.44668917 5.21848322 4.1466194
 2.64555612 7.74233689]
Rounded: [5.68 9.26 0.71 0.87 0.2  8.33 7.78 8.7  9.79 7.99 4.61 7.81 1.18 6.4
 1.43 9.45 5.22 4.15 2.65 7.74]
Min: 0.2021839744032572
Max: 9.78618342232764
Median: 6.039827912107281
After squaring elements < 5: [ 5.68044561  9.25596638  0.50461216  0.75915149  0.04087836  8.32619846
  7.78156751  8.70012148  9.78618342  7.99158564 21.29632018  7.80529176
  1.39888398  6.39921021  2.0550165   9.44668917  5.21848322 17.19445245
  6.99896719  7.74233689]
Alternately sorted: [0.20218397 9.78618342 0.71036058 9.44668917 0.871293   9.25596638
 1.18274426 8.70012148 1.43353287 8.32619846 2.64555612 7.99158564
 4.1466194  7.80529176 4.61479362 7.78156751 5.21848322 7.74233689
 5.68044561 6.39921021]


In [3]:
import pandas as pd
import random

# Create DataFrame
names = [f"Student{i+1}" for i in range(10)]
subjects = [random.choice(['Math', 'Science', 'English']) for _ in range(10)]
scores = np.random.randint(50, 101, 10)
df = pd.DataFrame({'Name': names, 'Subject': subjects, 'Score': scores, 'Grade': ['']*10})

# Assign grades
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'
df['Grade'] = df['Score'].apply(assign_grade)

# Print sorted DataFrame
df_sorted = df.sort_values('Score', ascending=False)
print(df_sorted)

# Average score per subject
avg_score_per_subject = df.groupby('Subject')['Score'].mean()
print("Average score per subject:\n", avg_score_per_subject)

# Filter A/B grades function
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

df_pass = pandas_filter_pass(df)
print("A/B grade records:\n", df_pass)


        Name  Subject  Score Grade
7   Student8     Math     90     A
6   Student7     Math     88     B
4   Student5  Science     86     B
1   Student2     Math     84     B
0   Student1     Math     78     C
8   Student9     Math     67     D
9  Student10     Math     65     D
5   Student6     Math     55     F
2   Student3     Math     50     F
3   Student4  English     50     F
Average score per subject:
 Subject
English    50.000
Math       72.125
Science    86.000
Name: Score, dtype: float64
A/B grade records:
        Name  Subject  Score Grade
1  Student2     Math     84     B
4  Student5  Science     86     B
6  Student7     Math     88     B
7  Student8     Math     90     A


In [15]:
import pandas as pd
import numpy as np
import random

# Define word pools
positive_words = ["fantastic", "amazing", "loved", "wonderful", "best", "awesome", "superb", "excellent", "happy", "delightful"]
negative_words = ["bad", "boring", "hated", "terrible", "awful", "worst", "poor", "disappointing", "dull", "mediocre", "frustrated", "unpleasant", "angry", "sad"]
neutral_words = ["movie", "plot", "scene", "character", "director", "actor", "music", "screenplay", "setting", "dialogue", "story", "tone", "background"]
noise_words = ["blur", "junk", "misc", "error", "random", "unknown", "static", "word", "noise"]

def generate_review(sentiment, n_sentiment=3, n_neutral=2, n_noise=2):
    if sentiment == 'positive':
        sent_words = random.sample(positive_words, n_sentiment)
    else:
        sent_words = random.sample(negative_words, n_sentiment)
    neutral = random.sample(neutral_words, n_neutral)
    noise = random.sample(noise_words, n_noise)
    words = sent_words + neutral + noise
    random.shuffle(words)
    return " ".join(words)

# Set reproducibility
random.seed(42)
np.random.seed(42)

# Generate reviews
n_samples = 100
n_pos = n_samples // 2
n_neg = n_samples - n_pos

reviews = [generate_review('positive') for _ in range(n_pos)] + [generate_review('negative') for _ in range(n_neg)]
sentiments = ['positive'] * n_pos + ['negative'] * n_neg

# Shuffle dataset
combined = list(zip(reviews, sentiments))
random.shuffle(combined)
reviews, sentiments = zip(*combined)

# Create DataFrame
movie_df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

# Tokenization
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(movie_df['Review'])
y = movie_df['Sentiment']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train classifier
model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Test accuracy:", accuracy)

# Prediction function
def predict_review_sentiment(model, vectorizer, review):
    X_new = vectorizer.transform([review])
    return model.predict(X_new)[0]


Test accuracy: 1.0


In [14]:
import pandas as pd
import numpy as np
import random

# Define word pools
positive_words = ["good", "satisfied", "happy", "excellent", "love", "recommend", "great", "pleased", "positive", "enjoy", "delightful", "superb", "fantastic", "wonderful", "awesome"]
negative_words = ["bad", "unsatisfied", "unhappy", "poor", "hate", "not recommend", "terrible", "displeased", "negative", "dislike", "frustrated", "awful", "worst", "mediocre", "sad"]
neutral_words = ["product", "service", "quality", "price", "delivery", "support", "experience", "feature", "design", "brand", "feedback", "purchase", "item", "order", "customer"]
noise_words = ["misc", "junk", "blur", "error", "random", "unknown", "static", "word", "noise"]

def generate_feedback(label, n_sentiment=3, n_neutral=2, n_noise=2):
    if label == 'good':
        sent_words = random.sample(positive_words, n_sentiment)
    else:
        sent_words = random.sample(negative_words, n_sentiment)
    neutral = random.sample(neutral_words, n_neutral)
    noise = random.sample(noise_words, n_noise)
    words = sent_words + neutral + noise
    random.shuffle(words)
    return " ".join(words)

# Set reproducibility
random.seed(42)
np.random.seed(42)

# Generate feedbacks
def create_feedback_dataset(n_samples=100):
    n_good = n_samples // 2
    n_bad = n_samples - n_good
    feedbacks = [generate_feedback('good') for _ in range(n_good)] + [generate_feedback('bad') for _ in range(n_bad)]
    labels = ['good'] * n_good + ['bad'] * n_bad
    # Shuffle dataset
    combined = list(zip(feedbacks, labels))
    random.shuffle(combined)
    feedbacks, labels = zip(*combined)
    df = pd.DataFrame({'Feedback': feedbacks, 'Label': labels})
    return df

feedback_df = create_feedback_dataset(100)

# TF-IDF vectorization
vectorizer2 = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X2 = vectorizer2.fit_transform(feedback_df['Feedback'])
y2 = feedback_df['Label']

# Split data
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.25, random_state=42)

# Train Logistic Regression
model2 = LogisticRegression(max_iter=200)
model2.fit(X2_train, y2_train)
y2_pred = model2.predict(X2_test)
precision, recall, f1, _ = precision_recall_fscore_support(y2_test, y2_pred, average='binary', pos_label='good')
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

# Preprocessing/vectorization function
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)


Precision: 1.0
Recall: 1.0
F1-score: 1.0
